before_script:
  - apt update -qq

  - apt install -y git make
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt install -y fsharp

stages:
  - buildAndInstall
  - compileScripts
  - test
  - package

buildAndInstall-1804:
  image: ubuntu:18.04
  stage: buildAndInstall
  script:
    - ./configure.sh
    - make
    - make install

buildAndInstall-2004:
  image: ubuntu:20.04
  stage: buildAndInstall
  script:
    - ./configure.sh
    - make
    - make install

compileScripts-1804:
  image: ubuntu:18.04
  stage: compileScripts
  script:
    - ./configure.sh && make install
    - ./ci-build.fsx

compileScripts-2004:
  image: ubuntu:20.04
  stage: compileScripts
  script:
    - ./configure.sh && make install
    - ./ci-build.fsx

test-1804:
  image: ubuntu:18.04
  stage: test
  script:
    - ./configure.sh && make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx

test-2004:
  image: ubuntu:20.04
  stage: test
  script:
    - ./configure.sh && make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx

package:
  image: ubuntu:20.04
  stage: package

  variables:
    # Fixes:
    # "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
    DOCKER_HOST: tcp://docker:2375
  services:
    # To support docker-in-docker
    - docker:dind

  script:
    - ./snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days
