image: ubuntu:18.04

before_script:
  - apt-get update -qq

  - apt-get install -y git
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt-get install -y fsharp

stages:
  - buildAndInstall
  - compileScripts
  - test
  - package

buildAndInstall:
  stage: buildAndInstall
  script:
    - ./configure.sh
    - make
    - make install

compileScripts:
  stage: compileScripts
  script:
    - ./ci-build.fsx

test:
  stage: test
  script:
    - ./configure.sh
    - make
    - make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx

package:
  stage: package
  script:
    - apt-get install -y snapcraft
    - ./snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days
