image: ubuntu:18.04

before_script:
  - apt-get update -qq

  - apt-get install -y git
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt-get install -y fsharp

build:
  script:
    - ./ci-build.fsx

install:
  script:
    - ./configure.fsx
    - make
    - make install

package:
  script:
    - apt-get install -y snapcraft
    - ./snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days

test:
  script:
    - ./configure.fsx
    - make
    - make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx
