before_script:
  - apt-get update -qq

  - apt-get install -y git
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt-get install -y fsharp

build_1804:
  image: ubuntu:18.04
  script:
    - ./ci-build.fsx

build_1904:
  image: ubuntu:19.04
  script:
    - ./ci-build.fsx

install:
  image: ubuntu:18.04
  script:
    - ./configure.sh
    - make
    - make install

package:
  image: ubuntu:18.04
  script:
    - apt-get install -y snapcraft
    - ./snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days

test:
  image: ubuntu:18.04
  script:
    - ./configure.sh
    - make
    - make install
    - ./test.fsx
    - ./testProcessConcurrency.fsx
