before_script:
  - apt update -qq
  - apt install -y git make

stages:
  - buildAndInstall
  - test
  - compileScripts
  - package

build&install-stockmono:
  image: ubuntu:20.04
  stage: buildAndInstall
  script:
    - ./scripts/CI/install_mono.sh

    - ./configure.sh
    - make
    - make install

build&install-newmono:
  image: ubuntu:20.04
  stage: buildAndInstall
  script:
    - ./scripts/CI/install_mono_from_microsoft_deb_packages.sh

    - ./configure.sh
    - make
    - make install

buildScripts-stockmono:
  image: ubuntu:20.04
  stage: compileScripts
  script:
    - ./scripts/CI/install_mono.sh

    - ./configure.sh && make install
    - ./scripts/test.sh
    - ./ci-build.fsx

buildScripts-newmono:
  image: ubuntu:20.04
  stage: compileScripts
  script:
    - ./scripts/CI/install_mono_from_microsoft_deb_packages.sh

    - ./configure.sh && make install
    - ./scripts/test.sh
    - ./ci-build.fsx

test-stockmono:
  image: ubuntu:20.04
  stage: test
  script:
    - ./scripts/CI/install_mono.sh

    - ./configure.sh && make install
    - ./scripts/test.sh

test-newmono:
  image: ubuntu:20.04
  stage: test
  script:
    - ./scripts/CI/install_mono_from_microsoft_deb_packages.sh

    - ./configure.sh && make install
    - ./scripts/test.sh

package:
  image: ubuntu:20.04
  stage: package

  variables:
    # Fixes:
    # "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
    DOCKER_HOST: tcp://docker:2375
  services:
    # To support docker-in-docker
    - docker:dind

  script:
    - ./scripts/snap_build.sh

  artifacts:
    paths:
      - fsx*.snap
    expire_in: 50days
