image: ubuntu:18.04

before_script:
  - apt-get update -qq

  # workaround to Ubuntu messing up with deps in STABLE/LTS
  - apt-get install -y tzdata

  - apt-get install -y git
  - apt-get install -y fsharp

stages:
  - build
  - test
  - deploy
  - testpkg

build:
  stage: build
  script:
    - ./ci-build.fsx

install:
  stage: deploy
  script:
    - ./configure.fsx
    - make
    - make install

package:
  stage: deploy
  script:
    - mkdir -p artifacts/bin
    - ./configure.fsx --prefix=./artifacts
    - make
    - make install

    # replace '$PREFIX/lib/fsx/fsxc.fsx.exe' path with '$SNAP/lib/fsx/fsxc.fsx.exe'
    # (which resolves to /snap/fsx/x1/lib/fsx/fsxc.fsx.exe)
    - sed -i 's/mono .*fsx.exe.*/mono \$SNAP\/lib\/fsx\/fsxc.fsx.exe "$1"/' artifacts/bin/fsx
    - apt-get install -y snapcraft 
    - snapcraft
    - mv fsx_constant_amd64.snap "fsx_$CI_COMMIT_REF_SLUG.snap"

    # to publish it in the snap store:
    # - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
    # - snapcraft login --with snapcraft.login
    # - snapcraft push *.snap --release edge

  artifacts:
    name: "fsx_$CI_COMMIT_REF_SLUG.snap"
    paths:
      - "fsx_$CI_COMMIT_REF_SLUG.snap"
    expire_in: 50 years
    
test:
  stage: test
  script:
    - ./configure.fsx
    - make
    - make install
    - ./test.fsx
    - ./testProcessToolsConcurrency.fsx

testpkg:
  stage: testpkg
  script:
    - snap install fsx_experiments-snap.snap
