name: fsx # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
# TODO: talk about versioning of snap package. explore automation ( best kept as manual task now)
version: 'constant' # just for humans, typically '1.2+git' or '1.3.2'
summary: F# scrpting tool # 79 char long summary
description: |
  FSX is the ideal tool for people that use F# for their scripting needs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  fsx:
    command: bin/fsx

parts:
  fsx:
    plugin: dump
    source: ./staging
    override-build: |
      echo "running sed"
      # binary is compiled at $SNAP/lib/fsx/fsxc.fsx.exe change the path in fsx shell script.
      sed -i 's/mono .*fsx.exe.*/mono \$SNAP\/lib\/fsx\/fsxc.fsx.exe "$1"/' bin/fsx
      snapcraftctl build

      
      
   
