name: CI

on: [push]

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure.sh
    - name: build in DEBUG mode
      run: make
    - name: install
      run: make install
    - name: run tests
      run: ./scripts/test.sh
