name: CI

on: [push, pull_request]

jobs:

  sanity_check:
    needs: [macOS, linux, windows]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
        fetch-depth: 0

    - name: Install dependencies of commitlint
      run: sudo apt install --yes npm && npm install @commitlint/config-conventional
    - name: Pull our commitlint configuration
      run: sudo apt install wget && wget https://raw.githubusercontent.com/nblockchain/conventions/master/commitlint.config.ts
    - name: Validate current commit (last commit) with commitlint
      run: npx commitlint --from HEAD~1 --to HEAD --verbose

    - name: Setup .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: fantomless
      run: |
        # NOTE: maintain fantomless version below in sync with .gitlab-ci.yml
        dotnet tool update --global fantomless-tool --version 4.7.996
        # path taken from https://stackoverflow.com/a/65367006/544947
        $HOME/.dotnet/tools/fantomless --recurse --check .

  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure.sh
    - name: build in DEBUG mode
      run: make

    - name: install
      run: |
        # to clean Debug artifacts first (make install builds in Release config)
        git clean -fdx

        ./configure.sh && sudo make install

    - name: run tests
      run: make check
    - name: compile this repo's .fsx scripts with fsx
      run: ./compileFSharpScripts.fsx

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: check mono version
      run: mono --version
    - name: install dependencies
      run: sudo apt install --yes fsharp
    - name: check mono version
      run: mono --version
    - name: configure
      run: ./configure.sh
    - name: build in DEBUG mode
      run: make

    - name: install
      run: |
        # to clean Debug artifacts first (make install builds in Release config)
        git clean -fdx

        ./configure.sh && sudo make install

    - name: run tests
      run: make check
    - name: compile this repo's .fsx scripts with fsx
      run: ./compileFSharpScripts.fsx

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: build in DEBUG mode
      run: .\make.bat
    - name: install
      run: .\make.bat install
    - name: run tests
      run: .\make.bat check
