name: CI

on: [push, pull_request]

jobs:

  style:
    needs: [macOS, linux, windows]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: fantomless
      run: |
        # NOTE: maintain fantomless version below in sync with .gitlab-ci.yml
        dotnet tool update --global fantomless-tool --version 4.7.996
        # path taken from https://stackoverflow.com/a/65367006/544947
        $HOME/.dotnet/tools/fantomless --recurse --check .

  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure.sh
    - name: build in DEBUG mode
      run: make

    - name: install
      run: |
        # to clean Debug artifacts first (make install builds in Release config)
        git clean -fdx

        ./configure.sh && sudo make install

    - name: run tests
      run: ./scripts/test.sh
    - name: compile this repo's .fsx scripts with fsx
      run: ./ci-build.fsx

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: check mono version
      run: mono --version
    - name: install dependencies
      run: sudo apt install --yes fsharp
    - name: check mono version
      run: mono --version
    - name: configure
      run: ./configure.sh
    - name: build in DEBUG mode
      run: make

    - name: install
      run: |
        # to clean Debug artifacts first (make install builds in Release config)
        git clean -fdx

        ./configure.sh && sudo make install

    - name: run tests
      run: ./scripts/test.sh
    - name: compile this repo's .fsx scripts with fsx
      run: ./ci-build.fsx

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build in DEBUG mode
      run: .\make.bat
    - name: install
      run: .\make.bat install
